Repository KTB-Sixmen/gitfolio_AI, pull requests merged in 2024-12, with the labels that each got.

#37 Feat: 이력서 수정
  .gitignore
  app/api/v1/routes.py
  app/config/settings.py
  app/dto/resume_modify_dto.py
  app/prompts/resume_prompt.py
  app/services/gpt_service.py
  app/services/json_service.py
Labels: feature

#46 [RE] ✨ feat : Jenkinsfile, 실제 cicd 는 파이프라인에서 할거라 주석처리함.
  .github/workflows/ai-cicd.yaml
  Jenkinsfile
Labels: duplicate

#53 refactor: develop 브랜치와 prod(main)브랜치 분리
  Dockerfile
  Jenkinsfile
  Jenkinsfile-prod
  docker-compose.yaml
Labels: refactor
